### ISSUE TITLE
agent: cri-endpoint does not get passed on update of agents

### ISSUE THREAD

**Issue by LiliC** [weaveworks/launcher#256]
On first run in the agents the correct cri-endpoint gets applied and the deployment gets started with those params, but once the update gets applied the cri-endpoint gets lost and the generic manifest file gets applied instead.

**Comment by LiliC** [comment]
Reopening issue again as sometimes this does not work for me. Not sure what the problem is. cc @dlespiau any ideas?

**Comment by dlespiau** [comment]
I noticed that `service` is serving an agent manifest with:

```
              args:
              - -agent.poll-url={{.Scheme}}://{{.LauncherHostname}}/k8s/agent.yaml?instanceID={{"{{.InstanceID}}"}}
              - -wc.hostname={{.WCHostname}}
              - -wc.token=$(WEAVE_CLOUD_TOKEN)
              - -agent.report-errors=true
              - -agent.cri-endpoint={{.CRIEndpoint}}
```

Note we always override the URL, so the default URL is not taken into account.

Instead of changing the default poll URL like in https://github.com/weaveworks/launcher/pull/257, I think we should amend the URL (add the cri-endpoint GET param) if `agent.cri-endpoing != ""`.
